version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:%5EFft%23D-n.1qiP%5D%24j@host.docker.internal:5432/postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: