version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - POSTGRES_CREDENTIALS={"username":"postgres","password":"gzPwHD32Dbsnkkx1J2","database":"postgres"}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: